"""file upload

Revision ID: 2db71fa5bcd6
Revises: 8448c9485543
Create Date: 2024-07-08 22:26:48.360714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db71fa5bcd6'
down_revision: Union[str, None] = '8448c9485543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_history', sa.Column('input_image', sa.LargeBinary(), nullable=True))
    op.add_column('production_history', sa.Column('reconstruct_image', sa.LargeBinary(), nullable=True))
    op.create_index(op.f('ix_production_history_input_image'), 'production_history', ['input_image'], unique=False)
    op.create_index(op.f('ix_production_history_reconstruct_image'), 'production_history', ['reconstruct_image'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_history_reconstruct_image'), table_name='production_history')
    op.drop_index(op.f('ix_production_history_input_image'), table_name='production_history')
    op.drop_column('production_history', 'reconstruct_image')
    op.drop_column('production_history', 'input_image')
    # ### end Alembic commands ###
