"""histry img

Revision ID: 3515950a2109
Revises: a373b68dc923
Create Date: 2024-07-09 21:08:50.605517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3515950a2109'
down_revision: Union[str, None] = 'a373b68dc923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_images', sa.Column('status', sa.Boolean(), nullable=True))
    op.alter_column('production_images', 'input_image',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('production_images', 'output_image',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.create_index(op.f('ix_production_images_status'), 'production_images', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_images_status'), table_name='production_images')
    op.alter_column('production_images', 'output_image',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('production_images', 'input_image',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.drop_column('production_images', 'status')
    # ### end Alembic commands ###
