"""add file name

Revision ID: 8448c9485543
Revises: 6011b992a421
Create Date: 2024-07-07 15:48:28.928349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8448c9485543'
down_revision: Union[str, None] = '6011b992a421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_history', sa.Column('file', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_production_history_file'), 'production_history', ['file'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_history_file'), table_name='production_history')
    op.drop_column('production_history', 'file')
    # ### end Alembic commands ###
