"""histry img remove status

Revision ID: 8bb920135f0b
Revises: 3515950a2109
Create Date: 2024-07-09 21:25:29.646301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8bb920135f0b'
down_revision: Union[str, None] = '3515950a2109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production_images', 'input_image',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('production_images', 'output_image',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.drop_index('ix_production_images_status', table_name='production_images')
    op.drop_column('production_images', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_images', sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.create_index('ix_production_images_status', 'production_images', ['status'], unique=False)
    op.alter_column('production_images', 'output_image',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('production_images', 'input_image',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
