"""Change columns to MEDIUMTEXT

Revision ID: a373b68dc923
Revises: abd4e1720098
Create Date: 2024-07-09 17:15:53.722584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a373b68dc923'
down_revision: Union[str, None] = 'abd4e1720098'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_image', sa.Text(length=16777215), nullable=True),
    sa.Column('output_image', sa.Text(length=16777215), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_images_history_id'), 'production_images', ['history_id'], unique=True)
    op.create_index(op.f('ix_production_images_id'), 'production_images', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_images_id'), table_name='production_images')
    op.drop_index(op.f('ix_production_images_history_id'), table_name='production_images')
    op.drop_table('production_images')
    # ### end Alembic commands ###
