"""Initial migration

Revision ID: aaec3b10bc8b
Revises: 
Create Date: 2024-07-07 14:37:36.215099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaec3b10bc8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('production_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_production_history_date'), 'production_history', ['date'], unique=False)
    op.create_index(op.f('ix_production_history_id'), 'production_history', ['id'], unique=False)
    op.create_index(op.f('ix_production_history_status'), 'production_history', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_production_history_status'), table_name='production_history')
    op.drop_index(op.f('ix_production_history_id'), table_name='production_history')
    op.drop_index(op.f('ix_production_history_date'), table_name='production_history')
    op.drop_table('production_history')
    # ### end Alembic commands ###
