"""remove column

Revision ID: abd4e1720098
Revises: ff2c1d61d080
Create Date: 2024-07-09 10:22:12.617712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd4e1720098'
down_revision: Union[str, None] = 'ff2c1d61d080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_production_history_input_image', table_name='production_history', mysql_length={'input_image': 3072})
    op.drop_index('ix_production_history_reconstruct_image', table_name='production_history', mysql_length={'reconstruct_image': 3072})
    op.drop_column('production_history', 'reconstruct_image')
    op.drop_column('production_history', 'input_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production_history', sa.Column('input_image', sa.BLOB(), nullable=True))
    op.add_column('production_history', sa.Column('reconstruct_image', sa.BLOB(), nullable=True))
    op.create_index('ix_production_history_reconstruct_image', 'production_history', ['reconstruct_image'], unique=False, mysql_length={'reconstruct_image': 3072})
    op.create_index('ix_production_history_input_image', 'production_history', ['input_image'], unique=False, mysql_length={'input_image': 3072})
    # ### end Alembic commands ###
